services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "7860:7860"
    environment:
      - PYTHONUNBUFFERED=1
      - GRADIO_SERVER_NAME=0.0.0.0
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  redis_data: